title:       "Operating Systems 2021-2 (OS212)"
version:     "Rolling"
copyright:   "2021-2021"
description: >- 
  Operating System class is based
author:           "Immanuel"
address:          "NONE"
sitemap:          "true"
plugins:
  - jekyll-sitemap
urlweb:           "https://Hzz-Hzz.github.io/os212/"
urlcontact:       "NONE"
urlgithub:        "https://github.com/Hzz-Hzz/os212/"
urlghpage:        "https://Hzz-Hzz.github.io/os212/"
keywords:         "jekyll, os, testing"
github:           
  - metadata